######################################################################
# Automatically generated by qmake (2.01a) mar nov 21 15:44:23 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lexer.h mainwindow.h parser.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp parser.cpp
RESOURCES += icons.qrc
